Added an error message in case the project configuration is not available.

diff --git a/bin/templates/draky.template b/bin/templates/draky.template
--- a/bin/templates/draky.template
+++ b/bin/templates/draky.template
@@ -38,6 +38,12 @@ find_project_config_path() {
 }
 
 PROJECT_CONFIG_PATH="$(find_project_config_path "$PROJECT_CONFIG_DIR")"
+
+if [ -z $PROJECT_CONFIG_PATH ]; then
+  echo -e "${COLOR_RED}Project configuration could not be found${COLOR_RESET}"
+  exit 1
+fi
+
 PROJECT_ROOT="$PROJECT_CONFIG_PATH/.."
 
 HOST_GLOBAL_CONFIG_PATH="$HOME/.draky"
@@ -77,7 +83,7 @@ start_core() {
       -e "DOCKER_HOST_IP=$DOCKER_HOST_IP"
     )
 
-    if [[ $DRAKY_DEVELOPMENT -eq 1 ]]; then
+    if [ $DRAKY_DEVELOPMENT -eq 1 ]; then
         ARGS+=(-v "$PROJECT_ROOT/core:/opt/dk-core")
     fi
 
